### ISSUE TITLE
loggers broke somewhere...

### ISSUE THREAD

**Issue by laroque** [project8/dripline#123]
Two examples follow

```
2015-08-24T13:26:18[ERROR   ] dripline.core.data_logger(126) -> traceback follows:
Traceback (most recent call last):
  File "/home/project8/python_environments/dripline_production_v1.6.x/local/lib/python2.7/site-packages/dripline-v1.6.4_5_g72cfe6d-py2.7.egg/dripline/core/data_logger.py", line 110, in _log_a_value
    val = self.get_value()
  File "/home/project8/python_environments/dripline_production_v1.6.x/local/lib/python2.7/site-packages/dripline-v1.6.4_5_g72cfe6d-py2.7.egg/dripline/core/endpoint.py", line 99, in wrapper
    cal = eval(eval_str, globals, locals)
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for ** or pow(): 'int' and 'tuple'
```

```
2015-08-24T13:26:20[ERROR   ] dripline.core.data_logger(126) -> traceback follows:
Traceback (most recent call last):
  File "/home/project8/python_environments/dripline_production_v1.6.x/local/lib/python2.7/site-packages/dripline-v1.6.4_5_g72cfe6d-py2.7.egg/dripline/core/data_logger.py", line 110, in _log_a_value
    val = self.get_value()
  File "/home/project8/python_environments/dripline_production_v1.6.x/local/lib/python2.7/site-packages/dripline-v1.6.4_5_g72cfe6d-py2.7.egg/dripline/core/endpoint.py", line 99, in wrapper
    cal = eval(eval_str, globals, locals)
  File "<string>", line 1, in <module>
TypeError: fabs() takes exactly one argument (2 given)
```

**Comment by laroque** [comment]
Not a dripline bug, problem was in muxer configuration... fixed in the configuration script.
