### ISSUE TITLE
communication is getting mangled

### ISSUE THREAD

**Issue by laroque** [project8/dripline#56]
These commands shouldn't get getting sent, what is this madness?

2015-01-26T15:01:06Z[DEBUG   ] dripline.instruments.prologix(127) -> sync: '*ES
R?\n' -> '+128\n'
2015-01-26T15:01:07Z[DEBUG   ] dripline.instruments.prologix(123) -> sending: +
*ESR? 6

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 760, in run
    self.function(*self.args, **self.kwargs)
  File "/home/project8/python_environments/production/local/lib/python2.7/site-
packages/dripline-0.0.2-py2.7.egg/dripline/instruments/prologix.py", line 105, 
in _check_next_status
    resp = self.send('*ESR?\n', from_spime=self._devices[device])
  File "/home/project8/python_environments/production/local/lib/python2.7/site-
packages/dripline-0.0.2-py2.7.egg/dripline/instruments/prologix.py", line 125, 
in send
    data = self.socket.recv(1024)
timeout: timed out

**Comment by laroque** [comment]
there has been some refactoring through all of this, not clear if this is still a problem but i've failed to reproduce so closing.
