### ISSUE TITLE
What happens when an amqp connection breaks

### ISSUE THREAD

**Issue by laroque** [project8/dripline#66]
2015-03-23T16:27:55Z[INFO    ] dripline.core.endpoint(184) -> set logging_status of my_price_list to on
2015-03-23T16:27:55Z[DEBUG   ] dripline.core.endpoint(174) -> reply sent
Traceback (most recent call last):
  File "/home/laroque/virt_env/sandbox/bin/open_spimescape_portal", line 7, in <module>
    execfile(__file__)
  File "/home/laroque/Repos/dripline/python/bin/open_spimescape_portal", line 57, in <module>
    open_spimescape_portal(**conf_dict)
  File "/home/laroque/Repos/dripline/python/bin/open_spimescape_portal", line 30, in open_spimescape_portal
    portal.start_event_loop()
  File "/home/laroque/Repos/dripline/python/dripline/core/portal.py", line 111, in start_event_loop
    self.conn.start()
  File "/home/laroque/Repos/dripline/python/dripline/core/connection.py", line 70, in start
    self.conn.process_data_events()
  File "/home/laroque/virt_env/sandbox/local/lib/python2.7/site-packages/pika-0.9.14-py2.7.egg/pika/adapters/blocking_connection.py", line 243, in process_data_events
    raise exceptions.ConnectionClosed()
pika.exceptions.ConnectionClosed

So it happens in dripline/core/connection.py line 70 -> self.conn.process_data_events()

**Comment by laroque** [comment]
Some thoughts for myself for later:

In any long running service:
```python
while True:
    try:
        do_the_consume_thing()
    except AMQP:
        reconnect()
        if not is_the_amqp_connection_fixed():
            tell_the_instrument_to_go_to_safe_mode()
            something_should_try_to_tweet_about_this()
    except Exception:
        print('something other than amqp broke, exiting')
        raise
```

Then, in the logger we have:
```python
def get_and_log_a_value_or_whatever_it_is_called():
    if amqp_connection_is_good:
        do_all_the_normal_get_then_log_things()
    schedule_the_next_logger_call()
```
which means if AMQP goes down for a little while, then comes back, the loggers don't break.
