### ISSUE TITLE
pid_loop crashes

### ISSUE THREAD

**Issue by ldeviveiros** [project8/dripline#76]
The pid_loop command crashes with the following error (inside the TMUX):
"
    value = reply.payload['value_cal']
TypeError: string indices must be integers, not str
"

We get the error when running the command:
pid_loop -v -b myrna.p8 -s cell_temp -o current_limit_heater -g 115 -m 0.300 -p 0.005 -d 5.0 -t pid_loop

to see the error, we must open the tmux session:
tmux attach -t pid_loop

**Comment by ldeviveiros** [comment]
Full error output:

"
(production)project8@claude:~$ /home/project8/python_environments/production/bin/pid_loop -v -b myrna.p8 -s cell_temp -o current_limit_heater -g 115 -m p 0.005 -d 5.0 
2015-05-15T16:56:13[INFO    ] pid_loop(135) ->  [*] Waiting for logs. To exit press CTRL+C
2015-05-15T16:56:13[INFO    ] dripline.core.connection(76) -> stopping consumption
Traceback (most recent call last):
  File "/home/project8/python_environments/production/bin/pid_loop", line 5, in <module>
    pkg_resources.run_script('dripline==1.4.1', 'pid_loop')
  File "/home/project8/python_environments/production/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 499, in run_
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/project8/python_environments/production/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1235, in run
    execfile(script_filename, namespace, namespace)
  File "/home/project8/python_environments/production/lib/python2.7/site-packages/dripline-1.4.1-py2.7.egg/EGG-INFO/scripts/pid_loop", line 209, in <mod
    start_monitoring(**vars(kwargs))
  File "/home/project8/python_environments/production/lib/python2.7/site-packages/dripline-1.4.1-py2.7.egg/EGG-INFO/scripts/pid_loop", line 138, in staroring
    pid = pid_controller(dripline_connection=dripline_connection, **kwargs)
  File "/home/project8/python_environments/production/lib/python2.7/site-packages/dripline-1.4.1-py2.7.egg/EGG-INFO/scripts/pid_loop", line 50, in __ini
    self._old_current = self.__get_old_current()
  File "/home/project8/python_environments/production/lib/python2.7/site-packages/dripline-1.4.1-py2.7.egg/EGG-INFO/scripts/pid_loop", line 59, in __getrrent
    value = reply.payload['value_cal']
TypeError: string indices must be integers, not str
(production)project8@claude:~$ 
"

**Comment by laroque** [comment]
there was some message payload parsing that need to update to match 1.4.x
